"""Rebuild data/zip_places.json from the free GeoNames US postal-code dataset.

The app needs to answer one question offline: "does this ZIP actually belong to
the city the user typed?" Hand-maintaining that list does not scale - there are
about 41,500 US ZIPs - so the whole set is bundled instead and refreshed with
this script.

Run it when the data feels stale (ZIP assignments change slowly; once a year is
generous):

    python scripts/refresh_zip_places.py

Requires internet. The app itself never does - it only reads the generated file.

Data source: https://download.geonames.org/export/zip/US.zip
License: Creative Commons Attribution 4.0 (credit to www.geonames.org).
"""

from __future__ import annotations

import io
import json
import sys
import urllib.request
import zipfile
from datetime import date
from pathlib import Path


SOURCE_URL = "https://download.geonames.org/export/zip/US.zip"
OUTPUT = Path(__file__).resolve().parent.parent / "data" / "zip_places.json"


def build() -> dict[str, list[str]]:
    print(f"Downloading {SOURCE_URL} ...")
    with urllib.request.urlopen(SOURCE_URL, timeout=120) as response:
        payload = response.read()
    print(f"  {len(payload) / 1024:.0f} KB downloaded")

    archive = zipfile.ZipFile(io.BytesIO(payload))
    places: dict[str, list[str]] = {}
    skipped = 0

    for line in archive.read("US.txt").decode("utf-8").splitlines():
        fields = line.split("\t")
        if len(fields) < 6:
            skipped += 1
            continue
        zip_code, city, state, county = fields[1], fields[2], fields[4], fields[5]
        if not zip_code or zip_code in places:
            # A ZIP can appear several times with alternate place names; the
            # first row is the primary one, which is what we want to compare against.
            continue
        places[zip_code] = [city, state, county]

    print(f"  {len(places)} unique ZIP codes ({skipped} malformed rows skipped)")
    return places


def main() -> int:
    try:
        places = build()
    except Exception as error:  # network, format, anything
        print(f"ERROR: could not rebuild the ZIP directory: {error}", file=sys.stderr)
        print("The existing data/zip_places.json was left untouched.", file=sys.stderr)
        return 1

    if len(places) < 30_000:
        print(
            f"ERROR: only {len(places)} ZIPs parsed, which looks wrong. "
            "Refusing to overwrite a good file with a bad one.",
            file=sys.stderr,
        )
        return 1

    document = {
        "_source": SOURCE_URL,
        "_license": "Creative Commons Attribution 4.0 - data (c) www.geonames.org",
        "_generated": date.today().isoformat(),
        "_note": "Generated by scripts/refresh_zip_places.py. Do not edit by hand.",
        "_format": "ZIP -> [city, state, county]",
        "places": places,
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        json.dumps(document, separators=(",", ":"), ensure_ascii=False),
        encoding="utf-8",
    )
    size_mb = OUTPUT.stat().st_size / 1024 / 1024
    print(f"Wrote {OUTPUT.relative_to(OUTPUT.parent.parent)} ({size_mb:.2f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
